# Generated by Django 5.2.6 on 2025-09-08 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(editable=False, max_length=100, unique=True)),
                ('key_name', models.CharField(max_length=100)),
                ('is_active_key', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeyBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_tokens', models.PositiveIntegerField(default=1000)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('max_token_limit', models.PositiveIntegerField(default=1000)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.apikey')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.apikey')),
            ],
        ),
    ]
